#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MapRoadTrafficSignal")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertWeekType(WeekType instance);
  partial void UpdateWeekType(WeekType instance);
  partial void DeleteWeekType(WeekType instance);
  partial void InsertItemGroup(ItemGroup instance);
  partial void UpdateItemGroup(ItemGroup instance);
  partial void DeleteItemGroup(ItemGroup instance);
  partial void InsertJob(Job instance);
  partial void UpdateJob(Job instance);
  partial void DeleteJob(Job instance);
  partial void InsertNotice(Notice instance);
  partial void UpdateNotice(Notice instance);
  partial void DeleteNotice(Notice instance);
  partial void InsertPermission(Permission instance);
  partial void UpdatePermission(Permission instance);
  partial void DeletePermission(Permission instance);
  partial void InsertTimeIntervalType(TimeIntervalType instance);
  partial void UpdateTimeIntervalType(TimeIntervalType instance);
  partial void DeleteTimeIntervalType(TimeIntervalType instance);
  partial void InsertTimeIntervalTypeDetail(TimeIntervalTypeDetail instance);
  partial void UpdateTimeIntervalTypeDetail(TimeIntervalTypeDetail instance);
  partial void DeleteTimeIntervalTypeDetail(TimeIntervalTypeDetail instance);
  partial void InsertTimePhase(TimePhase instance);
  partial void UpdateTimePhase(TimePhase instance);
  partial void DeleteTimePhase(TimePhase instance);
  partial void InsertTimePhaseDetail(TimePhaseDetail instance);
  partial void UpdateTimePhaseDetail(TimePhaseDetail instance);
  partial void DeleteTimePhaseDetail(TimePhaseDetail instance);
  partial void InsertTimePlan(TimePlan instance);
  partial void UpdateTimePlan(TimePlan instance);
  partial void DeleteTimePlan(TimePlan instance);
  partial void InsertUseItem(UseItem instance);
  partial void UpdateUseItem(UseItem instance);
  partial void DeleteUseItem(UseItem instance);
  partial void InsertIntersectionDetail(IntersectionDetail instance);
  partial void UpdateIntersectionDetail(IntersectionDetail instance);
  partial void DeleteIntersectionDetail(IntersectionDetail instance);
  partial void InsertIntersection(Intersection instance);
  partial void UpdateIntersection(Intersection instance);
  partial void DeleteIntersection(Intersection instance);
  partial void InsertUserLogin(UserLogin instance);
  partial void UpdateUserLogin(UserLogin instance);
  partial void DeleteUserLogin(UserLogin instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MapRoadTrafficSignalConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<WeekType> WeekType
	{
		get
		{
			return this.GetTable<WeekType>();
		}
	}
	
	public System.Data.Linq.Table<ItemGroup> ItemGroup
	{
		get
		{
			return this.GetTable<ItemGroup>();
		}
	}
	
	public System.Data.Linq.Table<Job> Job
	{
		get
		{
			return this.GetTable<Job>();
		}
	}
	
	public System.Data.Linq.Table<Notice> Notice
	{
		get
		{
			return this.GetTable<Notice>();
		}
	}
	
	public System.Data.Linq.Table<Permission> Permission
	{
		get
		{
			return this.GetTable<Permission>();
		}
	}
	
	public System.Data.Linq.Table<TimeIntervalType> TimeIntervalType
	{
		get
		{
			return this.GetTable<TimeIntervalType>();
		}
	}
	
	public System.Data.Linq.Table<TimeIntervalTypeDetail> TimeIntervalTypeDetail
	{
		get
		{
			return this.GetTable<TimeIntervalTypeDetail>();
		}
	}
	
	public System.Data.Linq.Table<TimePhase> TimePhase
	{
		get
		{
			return this.GetTable<TimePhase>();
		}
	}
	
	public System.Data.Linq.Table<TimePhaseDetail> TimePhaseDetail
	{
		get
		{
			return this.GetTable<TimePhaseDetail>();
		}
	}
	
	public System.Data.Linq.Table<TimePlan> TimePlan
	{
		get
		{
			return this.GetTable<TimePlan>();
		}
	}
	
	public System.Data.Linq.Table<TimePlanCycle> TimePlanCycle
	{
		get
		{
			return this.GetTable<TimePlanCycle>();
		}
	}
	
	public System.Data.Linq.Table<TimePlanExcel> TimePlanExcel
	{
		get
		{
			return this.GetTable<TimePlanExcel>();
		}
	}
	
	public System.Data.Linq.Table<TimePlanDetial> TimePlanDetial
	{
		get
		{
			return this.GetTable<TimePlanDetial>();
		}
	}
	
	public System.Data.Linq.Table<UseItem> UseItem
	{
		get
		{
			return this.GetTable<UseItem>();
		}
	}
	
	public System.Data.Linq.Table<IntersectionDetail> IntersectionDetail
	{
		get
		{
			return this.GetTable<IntersectionDetail>();
		}
	}
	
	public System.Data.Linq.Table<Intersection> Intersection
	{
		get
		{
			return this.GetTable<Intersection>();
		}
	}
	
	public System.Data.Linq.Table<UserLogin> UserLogin
	{
		get
		{
			return this.GetTable<UserLogin>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WeekType")]
public partial class WeekType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _WeekTypeID;
	
	private System.Nullable<int> _IntersectionDetailID;
	
	private string _Monday;
	
	private string _Tuesday;
	
	private string _Wednesday;
	
	private string _Thursday;
	
	private string _Friday;
	
	private string _Saturday;
	
	private string _Sunday;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWeekTypeIDChanging(int value);
    partial void OnWeekTypeIDChanged();
    partial void OnIntersectionDetailIDChanging(System.Nullable<int> value);
    partial void OnIntersectionDetailIDChanged();
    partial void OnMondayChanging(string value);
    partial void OnMondayChanged();
    partial void OnTuesdayChanging(string value);
    partial void OnTuesdayChanged();
    partial void OnWednesdayChanging(string value);
    partial void OnWednesdayChanged();
    partial void OnThursdayChanging(string value);
    partial void OnThursdayChanged();
    partial void OnFridayChanging(string value);
    partial void OnFridayChanged();
    partial void OnSaturdayChanging(string value);
    partial void OnSaturdayChanged();
    partial void OnSundayChanging(string value);
    partial void OnSundayChanged();
    #endregion
	
	public WeekType()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int WeekTypeID
	{
		get
		{
			return this._WeekTypeID;
		}
		set
		{
			if ((this._WeekTypeID != value))
			{
				this.OnWeekTypeIDChanging(value);
				this.SendPropertyChanging();
				this._WeekTypeID = value;
				this.SendPropertyChanged("WeekTypeID");
				this.OnWeekTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionDetailID", DbType="Int")]
	public System.Nullable<int> IntersectionDetailID
	{
		get
		{
			return this._IntersectionDetailID;
		}
		set
		{
			if ((this._IntersectionDetailID != value))
			{
				this.OnIntersectionDetailIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionDetailID = value;
				this.SendPropertyChanged("IntersectionDetailID");
				this.OnIntersectionDetailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="VarChar(10)")]
	public string Monday
	{
		get
		{
			return this._Monday;
		}
		set
		{
			if ((this._Monday != value))
			{
				this.OnMondayChanging(value);
				this.SendPropertyChanging();
				this._Monday = value;
				this.SendPropertyChanged("Monday");
				this.OnMondayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuesday", DbType="VarChar(10)")]
	public string Tuesday
	{
		get
		{
			return this._Tuesday;
		}
		set
		{
			if ((this._Tuesday != value))
			{
				this.OnTuesdayChanging(value);
				this.SendPropertyChanging();
				this._Tuesday = value;
				this.SendPropertyChanged("Tuesday");
				this.OnTuesdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wednesday", DbType="VarChar(10)")]
	public string Wednesday
	{
		get
		{
			return this._Wednesday;
		}
		set
		{
			if ((this._Wednesday != value))
			{
				this.OnWednesdayChanging(value);
				this.SendPropertyChanging();
				this._Wednesday = value;
				this.SendPropertyChanged("Wednesday");
				this.OnWednesdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thursday", DbType="VarChar(10)")]
	public string Thursday
	{
		get
		{
			return this._Thursday;
		}
		set
		{
			if ((this._Thursday != value))
			{
				this.OnThursdayChanging(value);
				this.SendPropertyChanging();
				this._Thursday = value;
				this.SendPropertyChanged("Thursday");
				this.OnThursdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="VarChar(10)")]
	public string Friday
	{
		get
		{
			return this._Friday;
		}
		set
		{
			if ((this._Friday != value))
			{
				this.OnFridayChanging(value);
				this.SendPropertyChanging();
				this._Friday = value;
				this.SendPropertyChanged("Friday");
				this.OnFridayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saturday", DbType="VarChar(10)")]
	public string Saturday
	{
		get
		{
			return this._Saturday;
		}
		set
		{
			if ((this._Saturday != value))
			{
				this.OnSaturdayChanging(value);
				this.SendPropertyChanging();
				this._Saturday = value;
				this.SendPropertyChanged("Saturday");
				this.OnSaturdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sunday", DbType="VarChar(10)")]
	public string Sunday
	{
		get
		{
			return this._Sunday;
		}
		set
		{
			if ((this._Sunday != value))
			{
				this.OnSundayChanging(value);
				this.SendPropertyChanging();
				this._Sunday = value;
				this.SendPropertyChanged("Sunday");
				this.OnSundayChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItemGroup")]
public partial class ItemGroup : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ItemGroupID;
	
	private string _ItemGroupName;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemGroupIDChanging(int value);
    partial void OnItemGroupIDChanged();
    partial void OnItemGroupNameChanging(string value);
    partial void OnItemGroupNameChanged();
    #endregion
	
	public ItemGroup()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemGroupID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ItemGroupID
	{
		get
		{
			return this._ItemGroupID;
		}
		set
		{
			if ((this._ItemGroupID != value))
			{
				this.OnItemGroupIDChanging(value);
				this.SendPropertyChanging();
				this._ItemGroupID = value;
				this.SendPropertyChanged("ItemGroupID");
				this.OnItemGroupIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemGroupName", DbType="NVarChar(50)")]
	public string ItemGroupName
	{
		get
		{
			return this._ItemGroupName;
		}
		set
		{
			if ((this._ItemGroupName != value))
			{
				this.OnItemGroupNameChanging(value);
				this.SendPropertyChanging();
				this._ItemGroupName = value;
				this.SendPropertyChanged("ItemGroupName");
				this.OnItemGroupNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Job")]
public partial class Job : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _JobID;
	
	private System.Nullable<int> _IntersectionID;
	
	private string _ZoneName;
	
	private System.Nullable<System.DateTime> _JobDate;
	
	private string _JobContent;
	
	private System.Nullable<System.DateTime> _RepairDate;
	
	private string _Src;
	
	private string _EmployeeID;
	
	private System.Nullable<System.DateTime> _ModifiedDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobIDChanging(int value);
    partial void OnJobIDChanged();
    partial void OnIntersectionIDChanging(System.Nullable<int> value);
    partial void OnIntersectionIDChanged();
    partial void OnZoneNameChanging(string value);
    partial void OnZoneNameChanged();
    partial void OnJobDateChanging(System.Nullable<System.DateTime> value);
    partial void OnJobDateChanged();
    partial void OnJobContentChanging(string value);
    partial void OnJobContentChanged();
    partial void OnRepairDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRepairDateChanged();
    partial void OnSrcChanging(string value);
    partial void OnSrcChanged();
    partial void OnEmployeeIDChanging(string value);
    partial void OnEmployeeIDChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    #endregion
	
	public Job()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int JobID
	{
		get
		{
			return this._JobID;
		}
		set
		{
			if ((this._JobID != value))
			{
				this.OnJobIDChanging(value);
				this.SendPropertyChanging();
				this._JobID = value;
				this.SendPropertyChanged("JobID");
				this.OnJobIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionID", DbType="Int")]
	public System.Nullable<int> IntersectionID
	{
		get
		{
			return this._IntersectionID;
		}
		set
		{
			if ((this._IntersectionID != value))
			{
				this.OnIntersectionIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionID = value;
				this.SendPropertyChanged("IntersectionID");
				this.OnIntersectionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneName", DbType="NVarChar(50)")]
	public string ZoneName
	{
		get
		{
			return this._ZoneName;
		}
		set
		{
			if ((this._ZoneName != value))
			{
				this.OnZoneNameChanging(value);
				this.SendPropertyChanging();
				this._ZoneName = value;
				this.SendPropertyChanged("ZoneName");
				this.OnZoneNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> JobDate
	{
		get
		{
			return this._JobDate;
		}
		set
		{
			if ((this._JobDate != value))
			{
				this.OnJobDateChanging(value);
				this.SendPropertyChanging();
				this._JobDate = value;
				this.SendPropertyChanged("JobDate");
				this.OnJobDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobContent", DbType="NVarChar(150)")]
	public string JobContent
	{
		get
		{
			return this._JobContent;
		}
		set
		{
			if ((this._JobContent != value))
			{
				this.OnJobContentChanging(value);
				this.SendPropertyChanging();
				this._JobContent = value;
				this.SendPropertyChanged("JobContent");
				this.OnJobContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepairDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> RepairDate
	{
		get
		{
			return this._RepairDate;
		}
		set
		{
			if ((this._RepairDate != value))
			{
				this.OnRepairDateChanging(value);
				this.SendPropertyChanging();
				this._RepairDate = value;
				this.SendPropertyChanged("RepairDate");
				this.OnRepairDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Src", DbType="NVarChar(100)")]
	public string Src
	{
		get
		{
			return this._Src;
		}
		set
		{
			if ((this._Src != value))
			{
				this.OnSrcChanging(value);
				this.SendPropertyChanging();
				this._Src = value;
				this.SendPropertyChanged("Src");
				this.OnSrcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="NVarChar(20)")]
	public string EmployeeID
	{
		get
		{
			return this._EmployeeID;
		}
		set
		{
			if ((this._EmployeeID != value))
			{
				this.OnEmployeeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeID = value;
				this.SendPropertyChanged("EmployeeID");
				this.OnEmployeeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime", IsDbGenerated=true)]
	public System.Nullable<System.DateTime> ModifiedDate
	{
		get
		{
			return this._ModifiedDate;
		}
		set
		{
			if ((this._ModifiedDate != value))
			{
				this.OnModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._ModifiedDate = value;
				this.SendPropertyChanged("ModifiedDate");
				this.OnModifiedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notice")]
public partial class Notice : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _NoticeID;
	
	private System.Nullable<int> _IntersectionID;
	
	private string _Who;
	
	private System.DateTime _NoticeDate;
	
	private string _NoticeContent;
	
	private string _Result;
	
	private string _Remark;
	
	private string _EmployeeID;
	
	private System.Nullable<System.DateTime> _ModifiedDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoticeIDChanging(int value);
    partial void OnNoticeIDChanged();
    partial void OnIntersectionIDChanging(System.Nullable<int> value);
    partial void OnIntersectionIDChanged();
    partial void OnWhoChanging(string value);
    partial void OnWhoChanged();
    partial void OnNoticeDateChanging(System.DateTime value);
    partial void OnNoticeDateChanged();
    partial void OnNoticeContentChanging(string value);
    partial void OnNoticeContentChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnEmployeeIDChanging(string value);
    partial void OnEmployeeIDChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    #endregion
	
	public Notice()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int NoticeID
	{
		get
		{
			return this._NoticeID;
		}
		set
		{
			if ((this._NoticeID != value))
			{
				this.OnNoticeIDChanging(value);
				this.SendPropertyChanging();
				this._NoticeID = value;
				this.SendPropertyChanged("NoticeID");
				this.OnNoticeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionID", DbType="Int")]
	public System.Nullable<int> IntersectionID
	{
		get
		{
			return this._IntersectionID;
		}
		set
		{
			if ((this._IntersectionID != value))
			{
				this.OnIntersectionIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionID = value;
				this.SendPropertyChanged("IntersectionID");
				this.OnIntersectionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Who", DbType="NVarChar(30)")]
	public string Who
	{
		get
		{
			return this._Who;
		}
		set
		{
			if ((this._Who != value))
			{
				this.OnWhoChanging(value);
				this.SendPropertyChanging();
				this._Who = value;
				this.SendPropertyChanged("Who");
				this.OnWhoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticeDate", DbType="DateTime NOT NULL")]
	public System.DateTime NoticeDate
	{
		get
		{
			return this._NoticeDate;
		}
		set
		{
			if ((this._NoticeDate != value))
			{
				this.OnNoticeDateChanging(value);
				this.SendPropertyChanging();
				this._NoticeDate = value;
				this.SendPropertyChanged("NoticeDate");
				this.OnNoticeDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticeContent", DbType="NVarChar(350)")]
	public string NoticeContent
	{
		get
		{
			return this._NoticeContent;
		}
		set
		{
			if ((this._NoticeContent != value))
			{
				this.OnNoticeContentChanging(value);
				this.SendPropertyChanging();
				this._NoticeContent = value;
				this.SendPropertyChanged("NoticeContent");
				this.OnNoticeContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="NVarChar(150)")]
	public string Result
	{
		get
		{
			return this._Result;
		}
		set
		{
			if ((this._Result != value))
			{
				this.OnResultChanging(value);
				this.SendPropertyChanging();
				this._Result = value;
				this.SendPropertyChanged("Result");
				this.OnResultChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(150)")]
	public string Remark
	{
		get
		{
			return this._Remark;
		}
		set
		{
			if ((this._Remark != value))
			{
				this.OnRemarkChanging(value);
				this.SendPropertyChanging();
				this._Remark = value;
				this.SendPropertyChanged("Remark");
				this.OnRemarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="NVarChar(20)")]
	public string EmployeeID
	{
		get
		{
			return this._EmployeeID;
		}
		set
		{
			if ((this._EmployeeID != value))
			{
				this.OnEmployeeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeID = value;
				this.SendPropertyChanged("EmployeeID");
				this.OnEmployeeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime", IsDbGenerated=true)]
	public System.Nullable<System.DateTime> ModifiedDate
	{
		get
		{
			return this._ModifiedDate;
		}
		set
		{
			if ((this._ModifiedDate != value))
			{
				this.OnModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._ModifiedDate = value;
				this.SendPropertyChanged("ModifiedDate");
				this.OnModifiedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Permission")]
public partial class Permission : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _PermissionID;
	
	private System.Nullable<int> _UserLoginID;
	
	private System.Nullable<int> _UseItemID;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPermissionIDChanging(int value);
    partial void OnPermissionIDChanged();
    partial void OnUserLoginIDChanging(System.Nullable<int> value);
    partial void OnUserLoginIDChanged();
    partial void OnUseItemIDChanging(System.Nullable<int> value);
    partial void OnUseItemIDChanged();
    #endregion
	
	public Permission()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int PermissionID
	{
		get
		{
			return this._PermissionID;
		}
		set
		{
			if ((this._PermissionID != value))
			{
				this.OnPermissionIDChanging(value);
				this.SendPropertyChanging();
				this._PermissionID = value;
				this.SendPropertyChanged("PermissionID");
				this.OnPermissionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginID", DbType="Int")]
	public System.Nullable<int> UserLoginID
	{
		get
		{
			return this._UserLoginID;
		}
		set
		{
			if ((this._UserLoginID != value))
			{
				this.OnUserLoginIDChanging(value);
				this.SendPropertyChanging();
				this._UserLoginID = value;
				this.SendPropertyChanged("UserLoginID");
				this.OnUserLoginIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseItemID", DbType="Int")]
	public System.Nullable<int> UseItemID
	{
		get
		{
			return this._UseItemID;
		}
		set
		{
			if ((this._UseItemID != value))
			{
				this.OnUseItemIDChanging(value);
				this.SendPropertyChanging();
				this._UseItemID = value;
				this.SendPropertyChanged("UseItemID");
				this.OnUseItemIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimeIntervalType")]
public partial class TimeIntervalType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _TimeIntervalTypeID;
	
	private System.Nullable<int> _IntersectionDetailID;
	
	private string _TimeType;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimeIntervalTypeIDChanging(int value);
    partial void OnTimeIntervalTypeIDChanged();
    partial void OnIntersectionDetailIDChanging(System.Nullable<int> value);
    partial void OnIntersectionDetailIDChanged();
    partial void OnTimeTypeChanging(string value);
    partial void OnTimeTypeChanged();
    #endregion
	
	public TimeIntervalType()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeIntervalTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int TimeIntervalTypeID
	{
		get
		{
			return this._TimeIntervalTypeID;
		}
		set
		{
			if ((this._TimeIntervalTypeID != value))
			{
				this.OnTimeIntervalTypeIDChanging(value);
				this.SendPropertyChanging();
				this._TimeIntervalTypeID = value;
				this.SendPropertyChanged("TimeIntervalTypeID");
				this.OnTimeIntervalTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionDetailID", DbType="Int")]
	public System.Nullable<int> IntersectionDetailID
	{
		get
		{
			return this._IntersectionDetailID;
		}
		set
		{
			if ((this._IntersectionDetailID != value))
			{
				this.OnIntersectionDetailIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionDetailID = value;
				this.SendPropertyChanged("IntersectionDetailID");
				this.OnIntersectionDetailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeType", DbType="VarChar(10)")]
	public string TimeType
	{
		get
		{
			return this._TimeType;
		}
		set
		{
			if ((this._TimeType != value))
			{
				this.OnTimeTypeChanging(value);
				this.SendPropertyChanging();
				this._TimeType = value;
				this.SendPropertyChanged("TimeType");
				this.OnTimeTypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimeIntervalTypeDetail")]
public partial class TimeIntervalTypeDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _TimeIntervalTypeDetailID;
	
	private System.Nullable<int> _TimeIntervalTypeID;
	
	private string _TimePlanSN;
	
	private string _Hour;
	
	private string _Minute;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimeIntervalTypeDetailIDChanging(int value);
    partial void OnTimeIntervalTypeDetailIDChanged();
    partial void OnTimeIntervalTypeIDChanging(System.Nullable<int> value);
    partial void OnTimeIntervalTypeIDChanged();
    partial void OnTimePlanSNChanging(string value);
    partial void OnTimePlanSNChanged();
    partial void OnHourChanging(string value);
    partial void OnHourChanged();
    partial void OnMinuteChanging(string value);
    partial void OnMinuteChanged();
    #endregion
	
	public TimeIntervalTypeDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeIntervalTypeDetailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int TimeIntervalTypeDetailID
	{
		get
		{
			return this._TimeIntervalTypeDetailID;
		}
		set
		{
			if ((this._TimeIntervalTypeDetailID != value))
			{
				this.OnTimeIntervalTypeDetailIDChanging(value);
				this.SendPropertyChanging();
				this._TimeIntervalTypeDetailID = value;
				this.SendPropertyChanged("TimeIntervalTypeDetailID");
				this.OnTimeIntervalTypeDetailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeIntervalTypeID", DbType="Int")]
	public System.Nullable<int> TimeIntervalTypeID
	{
		get
		{
			return this._TimeIntervalTypeID;
		}
		set
		{
			if ((this._TimeIntervalTypeID != value))
			{
				this.OnTimeIntervalTypeIDChanging(value);
				this.SendPropertyChanging();
				this._TimeIntervalTypeID = value;
				this.SendPropertyChanged("TimeIntervalTypeID");
				this.OnTimeIntervalTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePlanSN", DbType="VarChar(10)")]
	public string TimePlanSN
	{
		get
		{
			return this._TimePlanSN;
		}
		set
		{
			if ((this._TimePlanSN != value))
			{
				this.OnTimePlanSNChanging(value);
				this.SendPropertyChanging();
				this._TimePlanSN = value;
				this.SendPropertyChanged("TimePlanSN");
				this.OnTimePlanSNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hour", DbType="VarChar(10)")]
	public string Hour
	{
		get
		{
			return this._Hour;
		}
		set
		{
			if ((this._Hour != value))
			{
				this.OnHourChanging(value);
				this.SendPropertyChanging();
				this._Hour = value;
				this.SendPropertyChanged("Hour");
				this.OnHourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Minute", DbType="VarChar(10)")]
	public string Minute
	{
		get
		{
			return this._Minute;
		}
		set
		{
			if ((this._Minute != value))
			{
				this.OnMinuteChanging(value);
				this.SendPropertyChanging();
				this._Minute = value;
				this.SendPropertyChanged("Minute");
				this.OnMinuteChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimePhase")]
public partial class TimePhase : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _TimePhaseID;
	
	private System.Nullable<int> _IntersectionDetailID;
	
	private string _TimePhaseRoad;
	
	private string _ImgSrc;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimePhaseIDChanging(int value);
    partial void OnTimePhaseIDChanged();
    partial void OnIntersectionDetailIDChanging(System.Nullable<int> value);
    partial void OnIntersectionDetailIDChanged();
    partial void OnTimePhaseRoadChanging(string value);
    partial void OnTimePhaseRoadChanged();
    partial void OnImgSrcChanging(string value);
    partial void OnImgSrcChanged();
    #endregion
	
	public TimePhase()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePhaseID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int TimePhaseID
	{
		get
		{
			return this._TimePhaseID;
		}
		set
		{
			if ((this._TimePhaseID != value))
			{
				this.OnTimePhaseIDChanging(value);
				this.SendPropertyChanging();
				this._TimePhaseID = value;
				this.SendPropertyChanged("TimePhaseID");
				this.OnTimePhaseIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionDetailID", DbType="Int")]
	public System.Nullable<int> IntersectionDetailID
	{
		get
		{
			return this._IntersectionDetailID;
		}
		set
		{
			if ((this._IntersectionDetailID != value))
			{
				this.OnIntersectionDetailIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionDetailID = value;
				this.SendPropertyChanged("IntersectionDetailID");
				this.OnIntersectionDetailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePhaseRoad", DbType="VarChar(100)")]
	public string TimePhaseRoad
	{
		get
		{
			return this._TimePhaseRoad;
		}
		set
		{
			if ((this._TimePhaseRoad != value))
			{
				this.OnTimePhaseRoadChanging(value);
				this.SendPropertyChanging();
				this._TimePhaseRoad = value;
				this.SendPropertyChanged("TimePhaseRoad");
				this.OnTimePhaseRoadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgSrc", DbType="VarChar(100)")]
	public string ImgSrc
	{
		get
		{
			return this._ImgSrc;
		}
		set
		{
			if ((this._ImgSrc != value))
			{
				this.OnImgSrcChanging(value);
				this.SendPropertyChanging();
				this._ImgSrc = value;
				this.SendPropertyChanged("ImgSrc");
				this.OnImgSrcChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimePhaseDetail")]
public partial class TimePhaseDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _TimePhaseDetailID;
	
	private System.Nullable<int> _TimePhaseID;
	
	private string _TimePlanSN;
	
	private string _PH;
	
	private string _G;
	
	private string _Y;
	
	private string _R;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimePhaseDetailIDChanging(int value);
    partial void OnTimePhaseDetailIDChanged();
    partial void OnTimePhaseIDChanging(System.Nullable<int> value);
    partial void OnTimePhaseIDChanged();
    partial void OnTimePlanSNChanging(string value);
    partial void OnTimePlanSNChanged();
    partial void OnPHChanging(string value);
    partial void OnPHChanged();
    partial void OnGChanging(string value);
    partial void OnGChanged();
    partial void OnYChanging(string value);
    partial void OnYChanged();
    partial void OnRChanging(string value);
    partial void OnRChanged();
    #endregion
	
	public TimePhaseDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePhaseDetailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int TimePhaseDetailID
	{
		get
		{
			return this._TimePhaseDetailID;
		}
		set
		{
			if ((this._TimePhaseDetailID != value))
			{
				this.OnTimePhaseDetailIDChanging(value);
				this.SendPropertyChanging();
				this._TimePhaseDetailID = value;
				this.SendPropertyChanged("TimePhaseDetailID");
				this.OnTimePhaseDetailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePhaseID", DbType="Int")]
	public System.Nullable<int> TimePhaseID
	{
		get
		{
			return this._TimePhaseID;
		}
		set
		{
			if ((this._TimePhaseID != value))
			{
				this.OnTimePhaseIDChanging(value);
				this.SendPropertyChanging();
				this._TimePhaseID = value;
				this.SendPropertyChanged("TimePhaseID");
				this.OnTimePhaseIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePlanSN", DbType="VarChar(10)")]
	public string TimePlanSN
	{
		get
		{
			return this._TimePlanSN;
		}
		set
		{
			if ((this._TimePlanSN != value))
			{
				this.OnTimePlanSNChanging(value);
				this.SendPropertyChanging();
				this._TimePlanSN = value;
				this.SendPropertyChanged("TimePlanSN");
				this.OnTimePlanSNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PH", DbType="VarChar(100)")]
	public string PH
	{
		get
		{
			return this._PH;
		}
		set
		{
			if ((this._PH != value))
			{
				this.OnPHChanging(value);
				this.SendPropertyChanging();
				this._PH = value;
				this.SendPropertyChanged("PH");
				this.OnPHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G", DbType="VarChar(100)")]
	public string G
	{
		get
		{
			return this._G;
		}
		set
		{
			if ((this._G != value))
			{
				this.OnGChanging(value);
				this.SendPropertyChanging();
				this._G = value;
				this.SendPropertyChanged("G");
				this.OnGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y", DbType="VarChar(100)")]
	public string Y
	{
		get
		{
			return this._Y;
		}
		set
		{
			if ((this._Y != value))
			{
				this.OnYChanging(value);
				this.SendPropertyChanging();
				this._Y = value;
				this.SendPropertyChanged("Y");
				this.OnYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="VarChar(100)")]
	public string R
	{
		get
		{
			return this._R;
		}
		set
		{
			if ((this._R != value))
			{
				this.OnRChanging(value);
				this.SendPropertyChanging();
				this._R = value;
				this.SendPropertyChanged("R");
				this.OnRChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimePlan")]
public partial class TimePlan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _TimePlanID;
	
	private System.Nullable<int> _IntersectionDetailID;
	
	private string _TimePlanSN;
	
	private string _TimePhaseSN;
	
	private string _TimeDiff;
	
	private string _TimeCycle;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimePlanIDChanging(int value);
    partial void OnTimePlanIDChanged();
    partial void OnIntersectionDetailIDChanging(System.Nullable<int> value);
    partial void OnIntersectionDetailIDChanged();
    partial void OnTimePlanSNChanging(string value);
    partial void OnTimePlanSNChanged();
    partial void OnTimePhaseSNChanging(string value);
    partial void OnTimePhaseSNChanged();
    partial void OnTimeDiffChanging(string value);
    partial void OnTimeDiffChanged();
    partial void OnTimeCycleChanging(string value);
    partial void OnTimeCycleChanged();
    #endregion
	
	public TimePlan()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePlanID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int TimePlanID
	{
		get
		{
			return this._TimePlanID;
		}
		set
		{
			if ((this._TimePlanID != value))
			{
				this.OnTimePlanIDChanging(value);
				this.SendPropertyChanging();
				this._TimePlanID = value;
				this.SendPropertyChanged("TimePlanID");
				this.OnTimePlanIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionDetailID", DbType="Int")]
	public System.Nullable<int> IntersectionDetailID
	{
		get
		{
			return this._IntersectionDetailID;
		}
		set
		{
			if ((this._IntersectionDetailID != value))
			{
				this.OnIntersectionDetailIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionDetailID = value;
				this.SendPropertyChanged("IntersectionDetailID");
				this.OnIntersectionDetailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePlanSN", DbType="VarChar(10)")]
	public string TimePlanSN
	{
		get
		{
			return this._TimePlanSN;
		}
		set
		{
			if ((this._TimePlanSN != value))
			{
				this.OnTimePlanSNChanging(value);
				this.SendPropertyChanging();
				this._TimePlanSN = value;
				this.SendPropertyChanged("TimePlanSN");
				this.OnTimePlanSNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePhaseSN", DbType="VarChar(10)")]
	public string TimePhaseSN
	{
		get
		{
			return this._TimePhaseSN;
		}
		set
		{
			if ((this._TimePhaseSN != value))
			{
				this.OnTimePhaseSNChanging(value);
				this.SendPropertyChanging();
				this._TimePhaseSN = value;
				this.SendPropertyChanged("TimePhaseSN");
				this.OnTimePhaseSNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeDiff", DbType="VarChar(10)")]
	public string TimeDiff
	{
		get
		{
			return this._TimeDiff;
		}
		set
		{
			if ((this._TimeDiff != value))
			{
				this.OnTimeDiffChanging(value);
				this.SendPropertyChanging();
				this._TimeDiff = value;
				this.SendPropertyChanged("TimeDiff");
				this.OnTimeDiffChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCycle", DbType="VarChar(10)")]
	public string TimeCycle
	{
		get
		{
			return this._TimeCycle;
		}
		set
		{
			if ((this._TimeCycle != value))
			{
				this.OnTimeCycleChanging(value);
				this.SendPropertyChanging();
				this._TimeCycle = value;
				this.SendPropertyChanged("TimeCycle");
				this.OnTimeCycleChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimePlanCycle")]
public partial class TimePlanCycle
{
	
	private System.Nullable<int> _IntersectionDetailID;
	
	private string _TimePlanSN;
	
	private System.Nullable<int> _Cycle;
	
	public TimePlanCycle()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionDetailID", DbType="Int")]
	public System.Nullable<int> IntersectionDetailID
	{
		get
		{
			return this._IntersectionDetailID;
		}
		set
		{
			if ((this._IntersectionDetailID != value))
			{
				this._IntersectionDetailID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePlanSN", DbType="VarChar(10)")]
	public string TimePlanSN
	{
		get
		{
			return this._TimePlanSN;
		}
		set
		{
			if ((this._TimePlanSN != value))
			{
				this._TimePlanSN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cycle", DbType="Int")]
	public System.Nullable<int> Cycle
	{
		get
		{
			return this._Cycle;
		}
		set
		{
			if ((this._Cycle != value))
			{
				this._Cycle = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimePlanExcel")]
public partial class TimePlanExcel
{
	
	private System.Nullable<int> _IntersectionDetailID;
	
	private string _TimePlanSN;
	
	private string _G;
	
	private string _PH;
	
	private string _Y;
	
	private string _R;
	
	private int _TimePhaseID;
	
	public TimePlanExcel()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionDetailID", DbType="Int")]
	public System.Nullable<int> IntersectionDetailID
	{
		get
		{
			return this._IntersectionDetailID;
		}
		set
		{
			if ((this._IntersectionDetailID != value))
			{
				this._IntersectionDetailID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePlanSN", DbType="VarChar(10)")]
	public string TimePlanSN
	{
		get
		{
			return this._TimePlanSN;
		}
		set
		{
			if ((this._TimePlanSN != value))
			{
				this._TimePlanSN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G", DbType="VarChar(100)")]
	public string G
	{
		get
		{
			return this._G;
		}
		set
		{
			if ((this._G != value))
			{
				this._G = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PH", DbType="VarChar(100)")]
	public string PH
	{
		get
		{
			return this._PH;
		}
		set
		{
			if ((this._PH != value))
			{
				this._PH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y", DbType="VarChar(100)")]
	public string Y
	{
		get
		{
			return this._Y;
		}
		set
		{
			if ((this._Y != value))
			{
				this._Y = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="VarChar(100)")]
	public string R
	{
		get
		{
			return this._R;
		}
		set
		{
			if ((this._R != value))
			{
				this._R = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePhaseID", DbType="Int NOT NULL")]
	public int TimePhaseID
	{
		get
		{
			return this._TimePhaseID;
		}
		set
		{
			if ((this._TimePhaseID != value))
			{
				this._TimePhaseID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimePlanDetial")]
public partial class TimePlanDetial
{
	
	private System.Nullable<int> _IntersectionDetailID;
	
	private int _TimePhaseID;
	
	private string _TimePlanSN;
	
	private string _PH;
	
	private string _G;
	
	private string _Y;
	
	private string _R;
	
	private System.Nullable<int> _TimePhaseDetailID;
	
	public TimePlanDetial()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionDetailID", DbType="Int")]
	public System.Nullable<int> IntersectionDetailID
	{
		get
		{
			return this._IntersectionDetailID;
		}
		set
		{
			if ((this._IntersectionDetailID != value))
			{
				this._IntersectionDetailID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePhaseID", DbType="Int NOT NULL")]
	public int TimePhaseID
	{
		get
		{
			return this._TimePhaseID;
		}
		set
		{
			if ((this._TimePhaseID != value))
			{
				this._TimePhaseID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePlanSN", DbType="VarChar(10)")]
	public string TimePlanSN
	{
		get
		{
			return this._TimePlanSN;
		}
		set
		{
			if ((this._TimePlanSN != value))
			{
				this._TimePlanSN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PH", DbType="VarChar(10)")]
	public string PH
	{
		get
		{
			return this._PH;
		}
		set
		{
			if ((this._PH != value))
			{
				this._PH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G", DbType="VarChar(10)")]
	public string G
	{
		get
		{
			return this._G;
		}
		set
		{
			if ((this._G != value))
			{
				this._G = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y", DbType="VarChar(10)")]
	public string Y
	{
		get
		{
			return this._Y;
		}
		set
		{
			if ((this._Y != value))
			{
				this._Y = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="VarChar(10)")]
	public string R
	{
		get
		{
			return this._R;
		}
		set
		{
			if ((this._R != value))
			{
				this._R = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimePhaseDetailID", DbType="Int")]
	public System.Nullable<int> TimePhaseDetailID
	{
		get
		{
			return this._TimePhaseDetailID;
		}
		set
		{
			if ((this._TimePhaseDetailID != value))
			{
				this._TimePhaseDetailID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UseItem")]
public partial class UseItem : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UseItemID;
	
	private string _ItemName;
	
	private System.Nullable<int> _ItemGroupID;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUseItemIDChanging(int value);
    partial void OnUseItemIDChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    partial void OnItemGroupIDChanging(System.Nullable<int> value);
    partial void OnItemGroupIDChanged();
    #endregion
	
	public UseItem()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseItemID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int UseItemID
	{
		get
		{
			return this._UseItemID;
		}
		set
		{
			if ((this._UseItemID != value))
			{
				this.OnUseItemIDChanging(value);
				this.SendPropertyChanging();
				this._UseItemID = value;
				this.SendPropertyChanged("UseItemID");
				this.OnUseItemIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(50)")]
	public string ItemName
	{
		get
		{
			return this._ItemName;
		}
		set
		{
			if ((this._ItemName != value))
			{
				this.OnItemNameChanging(value);
				this.SendPropertyChanging();
				this._ItemName = value;
				this.SendPropertyChanged("ItemName");
				this.OnItemNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemGroupID", DbType="Int")]
	public System.Nullable<int> ItemGroupID
	{
		get
		{
			return this._ItemGroupID;
		}
		set
		{
			if ((this._ItemGroupID != value))
			{
				this.OnItemGroupIDChanging(value);
				this.SendPropertyChanging();
				this._ItemGroupID = value;
				this.SendPropertyChanged("ItemGroupID");
				this.OnItemGroupIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IntersectionDetail")]
public partial class IntersectionDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IntersectionDetailID;
	
	private System.Nullable<int> _IntersectionID;
	
	private string _Controller;
	
	private string _GPS;
	
	private string _Remark;
	
	private System.Nullable<System.DateTime> _VersionDate;
	
	private string _Src;
	
	private string _State;
	
	private string _EmployeeID;
	
	private string _TwoVer;
	
	private System.Nullable<System.DateTime> _ModifiedDate;
	
	private string _TrafficLightJson;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIntersectionDetailIDChanging(int value);
    partial void OnIntersectionDetailIDChanged();
    partial void OnIntersectionIDChanging(System.Nullable<int> value);
    partial void OnIntersectionIDChanged();
    partial void OnControllerChanging(string value);
    partial void OnControllerChanged();
    partial void OnGPSChanging(string value);
    partial void OnGPSChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnVersionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnVersionDateChanged();
    partial void OnSrcChanging(string value);
    partial void OnSrcChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnEmployeeIDChanging(string value);
    partial void OnEmployeeIDChanged();
    partial void OnTwoVerChanging(string value);
    partial void OnTwoVerChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnTrafficLightJsonChanging(string value);
    partial void OnTrafficLightJsonChanged();
    #endregion
	
	public IntersectionDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionDetailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IntersectionDetailID
	{
		get
		{
			return this._IntersectionDetailID;
		}
		set
		{
			if ((this._IntersectionDetailID != value))
			{
				this.OnIntersectionDetailIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionDetailID = value;
				this.SendPropertyChanged("IntersectionDetailID");
				this.OnIntersectionDetailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionID", DbType="Int")]
	public System.Nullable<int> IntersectionID
	{
		get
		{
			return this._IntersectionID;
		}
		set
		{
			if ((this._IntersectionID != value))
			{
				this.OnIntersectionIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionID = value;
				this.SendPropertyChanged("IntersectionID");
				this.OnIntersectionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Controller", DbType="NVarChar(20)")]
	public string Controller
	{
		get
		{
			return this._Controller;
		}
		set
		{
			if ((this._Controller != value))
			{
				this.OnControllerChanging(value);
				this.SendPropertyChanging();
				this._Controller = value;
				this.SendPropertyChanged("Controller");
				this.OnControllerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPS", DbType="VarChar(1)")]
	public string GPS
	{
		get
		{
			return this._GPS;
		}
		set
		{
			if ((this._GPS != value))
			{
				this.OnGPSChanging(value);
				this.SendPropertyChanging();
				this._GPS = value;
				this.SendPropertyChanged("GPS");
				this.OnGPSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(150)")]
	public string Remark
	{
		get
		{
			return this._Remark;
		}
		set
		{
			if ((this._Remark != value))
			{
				this.OnRemarkChanging(value);
				this.SendPropertyChanging();
				this._Remark = value;
				this.SendPropertyChanged("Remark");
				this.OnRemarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionDate", DbType="Date")]
	public System.Nullable<System.DateTime> VersionDate
	{
		get
		{
			return this._VersionDate;
		}
		set
		{
			if ((this._VersionDate != value))
			{
				this.OnVersionDateChanging(value);
				this.SendPropertyChanging();
				this._VersionDate = value;
				this.SendPropertyChanged("VersionDate");
				this.OnVersionDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Src", DbType="NVarChar(100)")]
	public string Src
	{
		get
		{
			return this._Src;
		}
		set
		{
			if ((this._Src != value))
			{
				this.OnSrcChanging(value);
				this.SendPropertyChanging();
				this._Src = value;
				this.SendPropertyChanged("Src");
				this.OnSrcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(1)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="NVarChar(20)")]
	public string EmployeeID
	{
		get
		{
			return this._EmployeeID;
		}
		set
		{
			if ((this._EmployeeID != value))
			{
				this.OnEmployeeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeID = value;
				this.SendPropertyChanged("EmployeeID");
				this.OnEmployeeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwoVer", DbType="VarChar(50)")]
	public string TwoVer
	{
		get
		{
			return this._TwoVer;
		}
		set
		{
			if ((this._TwoVer != value))
			{
				this.OnTwoVerChanging(value);
				this.SendPropertyChanging();
				this._TwoVer = value;
				this.SendPropertyChanged("TwoVer");
				this.OnTwoVerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime", IsDbGenerated=true)]
	public System.Nullable<System.DateTime> ModifiedDate
	{
		get
		{
			return this._ModifiedDate;
		}
		set
		{
			if ((this._ModifiedDate != value))
			{
				this.OnModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._ModifiedDate = value;
				this.SendPropertyChanged("ModifiedDate");
				this.OnModifiedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrafficLightJson", DbType="VarChar(MAX)")]
	public string TrafficLightJson
	{
		get
		{
			return this._TrafficLightJson;
		}
		set
		{
			if ((this._TrafficLightJson != value))
			{
				this.OnTrafficLightJsonChanging(value);
				this.SendPropertyChanging();
				this._TrafficLightJson = value;
				this.SendPropertyChanged("TrafficLightJson");
				this.OnTrafficLightJsonChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Intersection")]
public partial class Intersection : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IntersectionID;
	
	private string _Zone;
	
	private string _RoadName;
	
	private string _Position;
	
	private string _ENumber;
	
	private string _State;
	
	private string _EmployeeID;
	
	private System.Nullable<System.DateTime> _ModifiedDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIntersectionIDChanging(int value);
    partial void OnIntersectionIDChanged();
    partial void OnZoneChanging(string value);
    partial void OnZoneChanged();
    partial void OnRoadNameChanging(string value);
    partial void OnRoadNameChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnENumberChanging(string value);
    partial void OnENumberChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnEmployeeIDChanging(string value);
    partial void OnEmployeeIDChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    #endregion
	
	public Intersection()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntersectionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IntersectionID
	{
		get
		{
			return this._IntersectionID;
		}
		set
		{
			if ((this._IntersectionID != value))
			{
				this.OnIntersectionIDChanging(value);
				this.SendPropertyChanging();
				this._IntersectionID = value;
				this.SendPropertyChanged("IntersectionID");
				this.OnIntersectionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="NVarChar(20)")]
	public string Zone
	{
		get
		{
			return this._Zone;
		}
		set
		{
			if ((this._Zone != value))
			{
				this.OnZoneChanging(value);
				this.SendPropertyChanging();
				this._Zone = value;
				this.SendPropertyChanged("Zone");
				this.OnZoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoadName", DbType="NVarChar(20)")]
	public string RoadName
	{
		get
		{
			return this._RoadName;
		}
		set
		{
			if ((this._RoadName != value))
			{
				this.OnRoadNameChanging(value);
				this.SendPropertyChanging();
				this._RoadName = value;
				this.SendPropertyChanged("RoadName");
				this.OnRoadNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="VarChar(50)")]
	public string Position
	{
		get
		{
			return this._Position;
		}
		set
		{
			if ((this._Position != value))
			{
				this.OnPositionChanging(value);
				this.SendPropertyChanging();
				this._Position = value;
				this.SendPropertyChanged("Position");
				this.OnPositionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENumber", DbType="VarChar(30)")]
	public string ENumber
	{
		get
		{
			return this._ENumber;
		}
		set
		{
			if ((this._ENumber != value))
			{
				this.OnENumberChanging(value);
				this.SendPropertyChanging();
				this._ENumber = value;
				this.SendPropertyChanged("ENumber");
				this.OnENumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(1)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="VarChar(50)")]
	public string EmployeeID
	{
		get
		{
			return this._EmployeeID;
		}
		set
		{
			if ((this._EmployeeID != value))
			{
				this.OnEmployeeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeID = value;
				this.SendPropertyChanged("EmployeeID");
				this.OnEmployeeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime", IsDbGenerated=true)]
	public System.Nullable<System.DateTime> ModifiedDate
	{
		get
		{
			return this._ModifiedDate;
		}
		set
		{
			if ((this._ModifiedDate != value))
			{
				this.OnModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._ModifiedDate = value;
				this.SendPropertyChanged("ModifiedDate");
				this.OnModifiedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserLogin")]
public partial class UserLogin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UserLoginID;
	
	private string _UserID;
	
	private string _Password;
	
	private string _UserName;
	
	private string _JobTitle;
	
	private System.Nullable<System.DateTime> _ModifiedDate;
	
	private string _State;
	
	private string _admin;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserLoginIDChanging(int value);
    partial void OnUserLoginIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnadminChanging(string value);
    partial void OnadminChanged();
    #endregion
	
	public UserLogin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int UserLoginID
	{
		get
		{
			return this._UserLoginID;
		}
		set
		{
			if ((this._UserLoginID != value))
			{
				this.OnUserLoginIDChanging(value);
				this.SendPropertyChanging();
				this._UserLoginID = value;
				this.SendPropertyChanged("UserLoginID");
				this.OnUserLoginIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(50)")]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="NVarChar(50)")]
	public string JobTitle
	{
		get
		{
			return this._JobTitle;
		}
		set
		{
			if ((this._JobTitle != value))
			{
				this.OnJobTitleChanging(value);
				this.SendPropertyChanging();
				this._JobTitle = value;
				this.SendPropertyChanged("JobTitle");
				this.OnJobTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime", IsDbGenerated=true)]
	public System.Nullable<System.DateTime> ModifiedDate
	{
		get
		{
			return this._ModifiedDate;
		}
		set
		{
			if ((this._ModifiedDate != value))
			{
				this.OnModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._ModifiedDate = value;
				this.SendPropertyChanged("ModifiedDate");
				this.OnModifiedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(1)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="VarChar(1)")]
	public string admin
	{
		get
		{
			return this._admin;
		}
		set
		{
			if ((this._admin != value))
			{
				this.OnadminChanging(value);
				this.SendPropertyChanging();
				this._admin = value;
				this.SendPropertyChanged("admin");
				this.OnadminChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
